version: '3.8'

services:
  backend:
    build:
      context: ./Wiz_Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"       
    environment:
      - DATABASE_URL=postgresql://postgres:Mavericks2024!@database-1.cfmcu4ekyg1w.us-east-2.rds.amazonaws.com:5432/TTdatabase
      - FRONTEND_URL=http://localhost:3000

  frontend:
    build:
      context: ./my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000

volumes:
  db_data:
